---
title: "Sharpe Ratio Shiny"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}
library(flexdashboard)
library(highcharter)
library(tidyquant)
library(timetk)
library(shiny)
library(scales)
```

Sidebar {.sidebar}
=====================================
  
```{r}

fluidRow(
  column(7,
  textInput("stock1", "Stock 1", "SPY")),
  column(5,
  numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)  

fluidRow(
  column(7,
  textInput("stock2", "Stock 2", "EFA")),
  column(5,
  numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
  column(7,
  textInput("stock3", "Stock 3", "IJS")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(7,
  textInput("stock4", "Stock 4", "EEM")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(7,
  textInput("stock5", "Stock 5", "AGG")),
  column(5,
  numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)


fluidRow(
  column(7,
  dateInput("date", "Starting Date", "2013-01-01", format = "yyyy-mm-dd")))

fluidRow(
  column(5,
  numericInput("rfr", "RFR", .0003, min = 0, max = 1, step = .0002)),
  column(4,
  numericInput("window", "Window", 6, min = 3, max = 24, step = 2))
)

actionButton("go", "Submit")
```

```{r}
prices <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  getSymbols(symbols, src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
  `colnames<-`(symbols)
})

rfr <- eventReactive(input$go, {input$rfr})

window <- eventReactive(input$go, {input$window})

rolling_portfolio_sharpe_xts <- eventReactive(input$go, {
  
  validate(need(input$w1 + input$w2 + input$w3 + input$w4 + input$w5 == 100, 
                "The portfolio weights must sum to 100%!"))
  
  prices <- prices()
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  rfr <- rfr()
  
  window <- window()

prices_monthly <- to.monthly(prices, indexAt = "last", OHLC = FALSE)
asset_returns_xts <- na.omit(Return.calculate(prices_monthly, method = "log"))

portfolio_returns_xts_rebalanced_monthly <- Return.portfolio(asset_returns_xts, weights = w, rebalance_on = "months")

rolling_sharpe <- 
  rollapply(portfolio_returns_xts_rebalanced_monthly, window, 
                           function(x) SharpeRatio(x, Rf = rfr, FUN = "StdDev"))
})

portfolio_sharpe <- eventReactive(input$go, {
  
  validate(need(input$w1 + input$w2 + input$w3 + input$w4 + input$w5 == 100, "The portfolio weights must sum to 100%!"))
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  rfr <- rfr()
  
  portfolio_returns_sharpe <- 
      prices %>% 
      to.monthly(indexAt = "last", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns)))) %>% 
      tq_portfolio(assets_col = asset, 
               returns_col = returns, 
               weights = w,
               col_rename = "returns") %>% 
      slice(-1) %>%
      mutate(ratio = mean(returns - rfr)/sd(returns - rfr),
         returns_below_rfr = ifelse(returns < rfr, returns, NA),
         returns_above_rfr = ifelse(returns > rfr, returns, NA))

})


market_returns_sharpe <- eventReactive(input$go, {
  rfr <- rfr()
  
  market_returns_sharpe <- 
    getSymbols("SPY", src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`("SPY") %>% 
    to.monthly(indexAt = "last", OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
    mutate(returns = (log(SPY) - log(lag(SPY)))) %>% 
    na.omit() %>% 
    mutate(market_sharpe = mean(returns - rfr)/sd(returns - rfr))
  
})

```

Sharpe Ratio
=====================================  

Row {data-height=600}
-----------------------------------------------------------------------

### Rolling Sharpe

```{r}
renderHighchart({
  
  validate(need(input$go != 0, "Please choose your portfolio assets, weights, rfr, rolling window and start date and click submit."))
  
  market_returns_xts <- 
    market_returns_sharpe() %>% 
    select(date, returns) %>% 
    tk_xts(date_var = date)
  
  rfr <- rfr()
  window <- window()
  
  rolling_market_sharpe_xts <- 
    rollapply(market_returns_xts, window(), 
                           function(x) SharpeRatio(x, Rf = rfr, FUN = "StdDev"))
  
  highchart(type = "stock") %>%
  hc_title(text = "Rolling Sharpe") %>%
  hc_add_series(rolling_portfolio_sharpe_xts(), name = "Portfolio", color = "cornflowerblue") %>%
  hc_add_series(rolling_market_sharpe_xts, name = "Market", color = "green") %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) 

  
})
```


Row {data-height=190}
-----------------------------------------------------------------------

### The Sharpe Ratio of Your Portfolio

```{r}
renderValueBox({
  
  portfolio_sharpe <- portfolio_sharpe() %>% summarise(ratio = round(mean(ratio), 4))
  
  
  valueBox(value = tags$p(portfolio_sharpe, style = "font-size: 70%;"), color = "primary")
})

```

### Sharpe Ratio of S&P500 in same time period

```{r}
renderValueBox({
  
  market_sharpe <- market_returns_sharpe() %>% summarise(ratio = round(mean(market_sharpe), 4))
  
  valueBox(value = tags$p(market_sharpe, style = "font-size: 70%;"), color = "primary")
})

```

Row {.tabset .tabset-fade}
-------------------------------------

### Scatterplot

```{r, message = FALSE}
renderPlot({
  validate(need(input$go != 0, "Please choose your portfolio assets, weights, rfr, rolling window and start date and click submit."))
  rfr <- rfr()
  portfolio_sharpe <- portfolio_sharpe()
  
  ggplot(data = portfolio_sharpe, aes(x = date)) +
  geom_point(aes(y = returns_below_rfr), colour = "red") +
  geom_point(aes(y = returns_above_rfr), colour = "green") + 
  geom_vline(xintercept = as.numeric(as.Date("2016-11-30")), color = "blue") +
  geom_hline(yintercept = rfr, color = "purple", linetype = "dotted") +
  annotate(geom="text", x=as.Date("2016-11-30"), 
           y = -.05, label = "Trump", fontface = "plain", 
           angle = 90, alpha = .5, vjust =  1.5) +
  ylab("percent monthly returns")
})
```


### Histogram

```{r}
renderPlot({
  rfr <- rfr()
  portfolio_sharpe <- portfolio_sharpe()
  
  portfolio_sharpe %>% 
    ggplot(aes(x = returns)) +
    geom_histogram(alpha = 0.25, binwidth = .01, fill = "cornflowerblue") +
    geom_vline(xintercept = rfr, color = "green") +
    annotate(geom = "text", x = rfr, 
             y = 10, label = "rfr", fontface = "plain", 
             angle = 90, alpha = .5, vjust =  1)
})
```
