---
title: "Conclusion"
output: html_notebook
---

Shiny, and all data science, and the labratory analogy. Each Shiny app is a hypothesis. The underlying work is foundational, it's conclusive. It supports or it fails to support, our ideas. 

Two paradigms: team of ten, spend 1000 hours on 1 app. 

team of ten, build 20 apps, 50 hours each - see which one works the best, take the best, iterate. This probably maps onto a software or product dev roadmap. if so, great. I don't care about that - I care about what I have seen work in industry for R quant teams who productionize their work via Shiny or generate alpha, and this is the process that works. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

